# These github actions will perform linting and go tests
# spell-checker: disable
# yamllint disable rule:line-length
---
name: go-lint

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Verify go.mod and go.sum are up to date
        run: go mod tidy && git diff --exit-code -- go.mod go.sum
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Execute linter
        uses: golangci/golangci-lint-action@v5.1.0
        with:
          version: latest
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Download vesctl
        run: |
          curl -sfL https://vesio.azureedge.net/releases/vesctl/0.2.47/vesctl.linux-amd64.gz | sudo zcat > /usr/local/bin/vesctl
          sudo chmod 0755 /usr/local/bin/vesctl
          sudo chown root:root /usr/local/bin/vesctl
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run go tests
        run: go test -v ./...
