# spell-checker: disable
---
name: release-please

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release-please
        uses: GoogleCloudPlatform/release-please-action@v4.1.3
        with:
          release-type: go
          package-name: f5xc
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - name: Trigger Go Report update
        if: ${{ steps.release-please.outputs.release_created }}
        uses: fjogeleit/http-request-action@v1.16.3
        with:
          url: 'https://goreportcard.com/checks'
          method: 'POST'
          contentType: 'application/x-www-form-urlencoded'
          data: 'repo=github.com/${{ github.repository }}'
          preventFailureOnNoResponse: 'true'
